apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-app.fullname" . }}-flaresolverr
  labels:
    io.kompose.service: flaresolverr
  {{- include "docker-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.flaresolverr.type }}
  selector:
    io.kompose.service: flaresolverr
    {{- include "docker-app.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.flaresolverr.ports | toYaml | nindent 2 }}