apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "docker-app.fullname" . }}-claim0
  labels:
    io.kompose.service: suwayomi-claim0
  {{- include "docker-app.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.claim0.storageRequest | quote }}