apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "piraeus-operator.fullname" . }}-controller-manager
  labels:
  {{- include "piraeus-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "piraeus-operator.fullname" . }}-gencert
  labels:
  {{- include "piraeus-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.gencert.serviceAccount.annotations | nindent 4 }}